name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - mkdocs.yml
      - .github/workflows/docs.yml
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - SECURITY.md
      - CHANGELOG.md
      - README.md

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3.2.4
      - run: |
          uv python install
          uv run mkdocs gh-deploy --force
